import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/ui/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"], // sesuai figma
});

export const metadata: Metadata = {
  title: "Flowra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={`${poppins.className} flex flex-col min-h-screen font-poppins antialiased`}
      >
        <main className="flex-grow">
          {children}
        </main>
        <Footer /> 
      </body>
    </html>
  );
}
